/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostIdRouteImport } from './routes/post/$id'
import { Route as UserProfileUsernameRouteImport } from './routes/user/profile/$username'
import { Route as UserFeedExploreRouteImport } from './routes/user/feed/explore'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileUsernameRoute = UserProfileUsernameRouteImport.update({
  id: '/user/profile/$username',
  path: '/user/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const UserFeedExploreRoute = UserFeedExploreRouteImport.update({
  id: '/user/feed/explore',
  path: '/user/feed/explore',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/post/$id': typeof PostIdRoute
  '/user/feed/explore': typeof UserFeedExploreRoute
  '/user/profile/$username': typeof UserProfileUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/post/$id': typeof PostIdRoute
  '/user/feed/explore': typeof UserFeedExploreRoute
  '/user/profile/$username': typeof UserProfileUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/post/$id': typeof PostIdRoute
  '/user/feed/explore': typeof UserFeedExploreRoute
  '/user/profile/$username': typeof UserProfileUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/post/$id'
    | '/user/feed/explore'
    | '/user/profile/$username'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/post/$id' | '/user/feed/explore' | '/user/profile/$username'
  id:
    | '__root__'
    | '/'
    | '/post/$id'
    | '/user/feed/explore'
    | '/user/profile/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostIdRoute: typeof PostIdRoute
  UserFeedExploreRoute: typeof UserFeedExploreRoute
  UserProfileUsernameRoute: typeof UserProfileUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile/$username': {
      id: '/user/profile/$username'
      path: '/user/profile/$username'
      fullPath: '/user/profile/$username'
      preLoaderRoute: typeof UserProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/feed/explore': {
      id: '/user/feed/explore'
      path: '/user/feed/explore'
      fullPath: '/user/feed/explore'
      preLoaderRoute: typeof UserFeedExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostIdRoute: PostIdRoute,
  UserFeedExploreRoute: UserFeedExploreRoute,
  UserProfileUsernameRoute: UserProfileUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
