/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostIndexRouteImport } from './routes/post/index'
import { Route as UserProfileIndexRouteImport } from './routes/user/profile/index'
import { Route as UserFeedIndexRouteImport } from './routes/user/feed/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIndexRoute = PostIndexRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileIndexRoute = UserProfileIndexRouteImport.update({
  id: '/user/profile/',
  path: '/user/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserFeedIndexRoute = UserFeedIndexRouteImport.update({
  id: '/user/feed/',
  path: '/user/feed/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/post': typeof PostIndexRoute
  '/user/feed': typeof UserFeedIndexRoute
  '/user/profile': typeof UserProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/post': typeof PostIndexRoute
  '/user/feed': typeof UserFeedIndexRoute
  '/user/profile': typeof UserProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/post/': typeof PostIndexRoute
  '/user/feed/': typeof UserFeedIndexRoute
  '/user/profile/': typeof UserProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/post' | '/user/feed' | '/user/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/post' | '/user/feed' | '/user/profile'
  id: '__root__' | '/' | '/post/' | '/user/feed/' | '/user/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostIndexRoute: typeof PostIndexRoute
  UserFeedIndexRoute: typeof UserFeedIndexRoute
  UserProfileIndexRoute: typeof UserProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/': {
      id: '/post/'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile/': {
      id: '/user/profile/'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/feed/': {
      id: '/user/feed/'
      path: '/user/feed'
      fullPath: '/user/feed'
      preLoaderRoute: typeof UserFeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostIndexRoute: PostIndexRoute,
  UserFeedIndexRoute: UserFeedIndexRoute,
  UserProfileIndexRoute: UserProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
