/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserFeedRouteImport } from './routes/user/feed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UserFeedRoute = UserFeedRouteImport.update({
  id: '/user/feed',
  path: '/user/feed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user/feed': typeof UserFeedRoute
  '/user/profile': typeof UserProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user/feed': typeof UserFeedRoute
  '/user/profile': typeof UserProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/user/feed': typeof UserFeedRoute
  '/user/profile': typeof UserProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/user/feed' | '/user/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/user/feed' | '/user/profile'
  id: '__root__' | '/' | '/user/feed' | '/user/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserFeedRoute: typeof UserFeedRoute
  UserProfileRoute: typeof UserProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/feed': {
      id: '/user/feed'
      path: '/user/feed'
      fullPath: '/user/feed'
      preLoaderRoute: typeof UserFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserFeedRoute: UserFeedRoute,
  UserProfileRoute: UserProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
